version: '3'

services:
  nginx:
    image: nginx:1.15.5-alpine
    container_name: nginx-disposable-mailbox
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 80:80
    volumes:
      - php-storage:/var/www/html
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - disposable-mailbox

  disposable-mailbox:
    image: kolex/disposable-mailbox:0.2.1
    container_name: disposable-mailbox
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - php-storage:/var/www/html
      - ./src/config.php:/var/config.php

volumes:
  php-storage:

networks:
  internal:
